// <auto-generated />
using ClubEconomyControl.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubEconomyControl.Migrations
{
    [DbContext(typeof(ClubEconomyDbContext))]
    [Migration("20250905072250_AddDescriptionToEconomy")]
    partial class AddDescriptionToEconomy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClubEconomyControl.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SquadLimitEconomy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("ExtraordinaryExpenses");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("ExtraordinaryIncomes");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("OrdinaryExpenses");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("OrdinaryIncomes");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmortizationLeft")
                        .HasColumnType("int");

                    b.Property<int>("AnnualAmortization")
                        .HasColumnType("int");

                    b.Property<int?>("BoughtFromClubId")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("ContractEndtDate")
                        .HasColumnType("int");

                    b.Property<int>("ContractStartDate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SoldToClubId")
                        .HasColumnType("int");

                    b.Property<int>("TransferFeeBuy")
                        .HasColumnType("int");

                    b.Property<int>("TransferFeeSell")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoughtFromClubId");

                    b.HasIndex("ClubId");

                    b.HasIndex("SoldToClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryExpense", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("ExtraordinaryExpenses")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryIncome", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("ExtraordinaryIncomes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryExpense", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("OrdinaryExpenses")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryIncome", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("OrdinaryIncomes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Player", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "BoughtFromClub")
                        .WithMany()
                        .HasForeignKey("BoughtFromClubId");

                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubEconomyControl.Models.Club", "SoldToClub")
                        .WithMany()
                        .HasForeignKey("SoldToClubId");

                    b.Navigation("BoughtFromClub");

                    b.Navigation("Club");

                    b.Navigation("SoldToClub");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Club", b =>
                {
                    b.Navigation("ExtraordinaryExpenses");

                    b.Navigation("ExtraordinaryIncomes");

                    b.Navigation("OrdinaryExpenses");

                    b.Navigation("OrdinaryIncomes");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
