// <auto-generated />
using System;
using ClubEconomyControl.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubEconomyControl.Migrations
{
    [DbContext(typeof(ClubEconomyDbContext))]
    [Migration("20251030190012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClubEconomyControl.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SquadLimitEconomy")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerTransactionId");

                    b.ToTable("ExtraordinaryExpenses");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerTransactionId");

                    b.ToTable("ExtraordinaryIncomes");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("OrdinaryExpenses");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("OrdinaryIncomes");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualExpense")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("AnualAmortization")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("BoughtFromClub")
                        .HasColumnType("longtext");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RemainningAmortization")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SoldToClub")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TransferFeeBuy")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TransferFeeSell")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("isSelled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.PlayerTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerTransactions");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryExpense", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("ExtraordinaryExpenses")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubEconomyControl.Models.PlayerTransaction", "PlayerTransaction")
                        .WithMany()
                        .HasForeignKey("PlayerTransactionId");

                    b.Navigation("Club");

                    b.Navigation("PlayerTransaction");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.ExtraordinaryIncome", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("ExtraordinaryIncomes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubEconomyControl.Models.PlayerTransaction", "PlayerTransaction")
                        .WithMany()
                        .HasForeignKey("PlayerTransactionId");

                    b.Navigation("Club");

                    b.Navigation("PlayerTransaction");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryExpense", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("OrdinaryExpenses")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.OrdinaryIncome", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("OrdinaryIncomes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Player", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.PlayerTransaction", b =>
                {
                    b.HasOne("ClubEconomyControl.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubEconomyControl.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ClubEconomyControl.Models.Club", b =>
                {
                    b.Navigation("ExtraordinaryExpenses");

                    b.Navigation("ExtraordinaryIncomes");

                    b.Navigation("OrdinaryExpenses");

                    b.Navigation("OrdinaryIncomes");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
